export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  DOCS_SUBMITTED = 'DOCS_SUBMITTED',
  UNDER_VERIFICATION = 'UNDER_VERIFICATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEEDS_MORE_INFO = 'NEEDS_MORE_INFO',
}
