/**
 * Permission keys — GENERATED from backend/src/common/rbac/permission-catalog.ts.
 * Do not hand-edit; regenerate whenever the catalog changes.
 *
 * The backend is the authority: it rejects a forbidden call no matter what the UI thinks.
 * These keys exist only so the UI never renders a button that would come back 403.
 * Effective permissions come from GET /rbac/me at sign-in — never inferred from the role.
 */
export const Permission = {
  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  EXPORT_AUDIT_LOGS: 'EXPORT_AUDIT_LOGS',

  // Boarding
  VIEW_BOARDING_LIST: 'VIEW_BOARDING_LIST',
  SCAN_QR: 'SCAN_QR',
  MARK_BOARDED: 'MARK_BOARDED',
  MARK_NO_SHOW: 'MARK_NO_SHOW',

  // Booking
  SEARCH_BUSES: 'SEARCH_BUSES',
  CREATE_BOOKING: 'CREATE_BOOKING',
  EDIT_BOOKING: 'EDIT_BOOKING',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  HOLD_SEAT: 'HOLD_SEAT',
  VIEW_BOOKING: 'VIEW_BOOKING',
  SEARCH_BOOKING: 'SEARCH_BOOKING',
  VIEW_BOOKING_DASHBOARD: 'VIEW_BOOKING_DASHBOARD',

  // Bus
  CREATE_BUS: 'CREATE_BUS',
  EDIT_BUS: 'EDIT_BUS',
  DELETE_BUS: 'DELETE_BUS',
  VIEW_BUS: 'VIEW_BUS',
  ACTIVATE_BUS: 'ACTIVATE_BUS',
  CREATE_SEAT_LAYOUT: 'CREATE_SEAT_LAYOUT',

  // Crew HR
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  MANAGE_SHIFT: 'MANAGE_SHIFT',
  MANAGE_DUTY_ROSTER: 'MANAGE_DUTY_ROSTER',
  MANAGE_ATTENDANCE: 'MANAGE_ATTENDANCE',
  APPROVE_LEAVE: 'APPROVE_LEAVE',

  // Disruption
  CREATE_DISRUPTION: 'CREATE_DISRUPTION',
  CLOSE_DISRUPTION: 'CLOSE_DISRUPTION',
  DIVERT_ROUTE: 'DIVERT_ROUTE',
  DEPLOY_BACKUP: 'DEPLOY_BACKUP',
  VIEW_DISRUPTION_DASHBOARD: 'VIEW_DISRUPTION_DASHBOARD',
  RECORD_RCA: 'RECORD_RCA',

  // Driver Compliance
  CREATE_DRIVER: 'CREATE_DRIVER',
  EDIT_DRIVER: 'EDIT_DRIVER',
  UPLOAD_DRIVER_DOCUMENTS: 'UPLOAD_DRIVER_DOCUMENTS',
  RECORD_DRIVER_VIOLATION: 'RECORD_DRIVER_VIOLATION',
  ASSIGN_DRIVER_TRAINING: 'ASSIGN_DRIVER_TRAINING',
  VIEW_DRIVER_COMPLIANCE_DASHBOARD: 'VIEW_DRIVER_COMPLIANCE_DASHBOARD',
  VIEW_EXPIRING_DOCS: 'VIEW_EXPIRING_DOCS',

  // Fleet Maintenance
  CREATE_WORK_ORDER: 'CREATE_WORK_ORDER',
  APPROVE_WORK_ORDER: 'APPROVE_WORK_ORDER',
  MANAGE_PARTS_INVENTORY: 'MANAGE_PARTS_INVENTORY',
  MANAGE_VEHICLE_DOCS: 'MANAGE_VEHICLE_DOCS',
  VIEW_VEHICLE_HEALTH: 'VIEW_VEHICLE_HEALTH',

  // Forecasting
  GENERATE_FORECAST: 'GENERATE_FORECAST',
  VIEW_FORECAST_DASHBOARD: 'VIEW_FORECAST_DASHBOARD',

  // Fuel
  CREATE_FUEL_TXN: 'CREATE_FUEL_TXN',
  APPROVE_FUEL_TXN: 'APPROVE_FUEL_TXN',
  MANAGE_FUEL_CARD: 'MANAGE_FUEL_CARD',
  VIEW_FUEL_REPORTS: 'VIEW_FUEL_REPORTS',

  // Hub
  MANAGE_HUB: 'MANAGE_HUB',
  VIEW_HUB: 'VIEW_HUB',
  MANAGE_HUB_ROUTE: 'MANAGE_HUB_ROUTE',

  // Operator Finance
  VIEW_FINANCIAL_DASHBOARD: 'VIEW_FINANCIAL_DASHBOARD',
  VIEW_LEDGER: 'VIEW_LEDGER',
  CREATE_INVOICE: 'CREATE_INVOICE',
  VIEW_GST_REPORTS: 'VIEW_GST_REPORTS',
  VIEW_REVENUE_REPORTS: 'VIEW_REVENUE_REPORTS',
  CLOSE_FINANCIAL_PERIOD: 'CLOSE_FINANCIAL_PERIOD',

  // Operator Staff
  MANAGE_COUNTER: 'MANAGE_COUNTER',
  VIEW_COUNTER: 'VIEW_COUNTER',
  COUNTER_SALE: 'COUNTER_SALE',
  CREATE_OPERATOR_STAFF: 'CREATE_OPERATOR_STAFF',
  EDIT_OPERATOR_STAFF: 'EDIT_OPERATOR_STAFF',
  VIEW_STAFF_LIST: 'VIEW_STAFF_LIST',
  CONFIGURE_STAFF_PERMISSIONS: 'CONFIGURE_STAFF_PERMISSIONS',

  // Passenger Transfer
  INITIATE_PASSENGER_TRANSFER: 'INITIATE_PASSENGER_TRANSFER',
  APPROVE_PASSENGER_TRANSFER: 'APPROVE_PASSENGER_TRANSFER',
  REGENERATE_TICKET: 'REGENERATE_TICKET',
  VIEW_TRANSFER_REPORTS: 'VIEW_TRANSFER_REPORTS',

  // Platform Analytics
  VIEW_EXECUTIVE_DASHBOARD: 'VIEW_EXECUTIVE_DASHBOARD',
  VIEW_CROSS_OPERATOR_ANALYTICS: 'VIEW_CROSS_OPERATOR_ANALYTICS',
  VIEW_PLATFORM_AUDIT_LOGS: 'VIEW_PLATFORM_AUDIT_LOGS',

  // Platform API
  CREATE_API_PARTNER: 'CREATE_API_PARTNER',
  APPROVE_API_PARTNER: 'APPROVE_API_PARTNER',
  SUSPEND_API_PARTNER: 'SUSPEND_API_PARTNER',
  GENERATE_API_KEY: 'GENERATE_API_KEY',
  REVOKE_API_KEY: 'REVOKE_API_KEY',
  CONFIGURE_WEBHOOKS: 'CONFIGURE_WEBHOOKS',
  MANAGE_API_VERSIONS: 'MANAGE_API_VERSIONS',
  VIEW_API_USAGE: 'VIEW_API_USAGE',

  // Platform Billing
  CREATE_SAAS_INVOICE: 'CREATE_SAAS_INVOICE',
  VOID_SAAS_INVOICE: 'VOID_SAAS_INVOICE',
  RECORD_SAAS_PAYMENT: 'RECORD_SAAS_PAYMENT',
  CREATE_SAAS_CREDIT_NOTE: 'CREATE_SAAS_CREDIT_NOTE',
  CREATE_SAAS_DEBIT_NOTE: 'CREATE_SAAS_DEBIT_NOTE',
  VIEW_SAAS_LEDGER: 'VIEW_SAAS_LEDGER',

  // Platform Compliance
  PROCESS_DATA_ACCESS_REQUEST: 'PROCESS_DATA_ACCESS_REQUEST',
  PROCESS_DATA_DELETION_REQUEST: 'PROCESS_DATA_DELETION_REQUEST',
  CONFIGURE_CONSENT: 'CONFIGURE_CONSENT',
  VIEW_COMPLIANCE_DASHBOARD: 'VIEW_COMPLIANCE_DASHBOARD',
  CONFIGURE_ENCRYPTION_KEYS: 'CONFIGURE_ENCRYPTION_KEYS',

  // Platform Config
  CONFIGURE_PLATFORM_SETTINGS: 'CONFIGURE_PLATFORM_SETTINGS',
  CONFIGURE_FEATURE_FLAGS: 'CONFIGURE_FEATURE_FLAGS',
  CONFIGURE_MAINTENANCE_WINDOW: 'CONFIGURE_MAINTENANCE_WINDOW',
  ENABLE_MAINTENANCE_MODE: 'ENABLE_MAINTENANCE_MODE',
  VIEW_CONFIG_VERSIONS: 'VIEW_CONFIG_VERSIONS',
  RESTORE_CONFIG_VERSION: 'RESTORE_CONFIG_VERSION',

  // Platform Marketplace
  CREATE_PARTNER_ACCOUNT: 'CREATE_PARTNER_ACCOUNT',
  APPROVE_PARTNER: 'APPROVE_PARTNER',
  SUSPEND_PARTNER: 'SUSPEND_PARTNER',
  CONFIGURE_PARTNER_COMMISSION: 'CONFIGURE_PARTNER_COMMISSION',
  CONFIGURE_REVENUE_SHARING: 'CONFIGURE_REVENUE_SHARING',
  VIEW_MARKETPLACE_ANALYTICS: 'VIEW_MARKETPLACE_ANALYTICS',

  // Platform Operator
  CREATE_OPERATOR: 'CREATE_OPERATOR',
  EDIT_OPERATOR: 'EDIT_OPERATOR',
  SUSPEND_OPERATOR: 'SUSPEND_OPERATOR',
  ACTIVATE_OPERATOR: 'ACTIVATE_OPERATOR',
  DELETE_OPERATOR: 'DELETE_OPERATOR',
  VIEW_OPERATOR: 'VIEW_OPERATOR',
  CONFIGURE_OPERATOR_FEATURES: 'CONFIGURE_OPERATOR_FEATURES',
  VIEW_OPERATOR_USAGE: 'VIEW_OPERATOR_USAGE',
  PROVISION_OPERATOR: 'PROVISION_OPERATOR',
  PURGE_OPERATOR_DATA: 'PURGE_OPERATOR_DATA',
  VIEW_CROSS_OPERATOR_DASHBOARD: 'VIEW_CROSS_OPERATOR_DASHBOARD',

  // Platform Reliability
  VIEW_SYSTEM_HEALTH: 'VIEW_SYSTEM_HEALTH',
  VIEW_BACKGROUND_JOBS: 'VIEW_BACKGROUND_JOBS',
  MANAGE_BACKGROUND_JOBS: 'MANAGE_BACKGROUND_JOBS',
  SCHEDULE_SYSTEM_JOB: 'SCHEDULE_SYSTEM_JOB',
  APPROVE_DEPLOYMENT: 'APPROVE_DEPLOYMENT',
  ROLLBACK_DEPLOYMENT: 'ROLLBACK_DEPLOYMENT',

  // Platform Subscription
  CREATE_SUBSCRIPTION_PLAN: 'CREATE_SUBSCRIPTION_PLAN',
  EDIT_SUBSCRIPTION_PLAN: 'EDIT_SUBSCRIPTION_PLAN',
  DELETE_SUBSCRIPTION_PLAN: 'DELETE_SUBSCRIPTION_PLAN',
  ACTIVATE_SUBSCRIPTION_PLAN: 'ACTIVATE_SUBSCRIPTION_PLAN',
  ASSIGN_SUBSCRIPTION: 'ASSIGN_SUBSCRIPTION',
  CHANGE_SUBSCRIPTION_PLAN: 'CHANGE_SUBSCRIPTION_PLAN',
  RENEW_SUBSCRIPTION: 'RENEW_SUBSCRIPTION',
  EXTEND_TRIAL: 'EXTEND_TRIAL',
  SUSPEND_SUBSCRIPTION: 'SUSPEND_SUBSCRIPTION',
  VIEW_SUBSCRIPTION: 'VIEW_SUBSCRIPTION',
  VIEW_MRR_ARR: 'VIEW_MRR_ARR',

  // Platform User Security
  CREATE_PLATFORM_USER: 'CREATE_PLATFORM_USER',
  EDIT_PLATFORM_USER: 'EDIT_PLATFORM_USER',
  SUSPEND_PLATFORM_USER: 'SUSPEND_PLATFORM_USER',
  RESET_USER_PASSWORD: 'RESET_USER_PASSWORD',
  ASSIGN_ROLE: 'ASSIGN_ROLE',
  IMPERSONATE_USER: 'IMPERSONATE_USER',
  VIEW_LOGIN_HISTORY: 'VIEW_LOGIN_HISTORY',
  VIEW_SECURITY_DASHBOARD: 'VIEW_SECURITY_DASHBOARD',

  // Pricing
  MANAGE_COUPON: 'MANAGE_COUPON',
  VIEW_COUPON: 'VIEW_COUPON',
  CREATE_FARE_RULE: 'CREATE_FARE_RULE',
  CONFIGURE_DYNAMIC_PRICING: 'CONFIGURE_DYNAMIC_PRICING',
  VIEW_FARE_CALENDAR: 'VIEW_FARE_CALENDAR',

  // Refund
  CREATE_REFUND_REQUEST: 'CREATE_REFUND_REQUEST',
  APPROVE_REFUND: 'APPROVE_REFUND',
  PROCESS_REFUND: 'PROCESS_REFUND',
  VIEW_REFUND_STATUS: 'VIEW_REFUND_STATUS',

  // Reports
  VIEW_OPERATIONS_DASHBOARD: 'VIEW_OPERATIONS_DASHBOARD',
  CREATE_CUSTOM_REPORT: 'CREATE_CUSTOM_REPORT',
  VIEW_OCCUPANCY_REPORT: 'VIEW_OCCUPANCY_REPORT',

  // Route
  CREATE_ROUTE: 'CREATE_ROUTE',
  EDIT_ROUTE: 'EDIT_ROUTE',
  DELETE_ROUTE: 'DELETE_ROUTE',
  VIEW_ROUTE: 'VIEW_ROUTE',
  MANAGE_ROUTE_STOPS: 'MANAGE_ROUTE_STOPS',

  // Schedule
  CREATE_SCHEDULE: 'CREATE_SCHEDULE',
  EDIT_SCHEDULE: 'EDIT_SCHEDULE',
  VIEW_SCHEDULE: 'VIEW_SCHEDULE',
  ACTIVATE_SCHEDULE: 'ACTIVATE_SCHEDULE',

  // Seat Inventory
  BLOCK_SEATS: 'BLOCK_SEATS',
  VIEW_SEAT_INVENTORY: 'VIEW_SEAT_INVENTORY',

  // Seat Upgrade
  OFFER_SEAT_UPGRADE: 'OFFER_SEAT_UPGRADE',
  APPROVE_SEAT_UPGRADE: 'APPROVE_SEAT_UPGRADE',
  VIEW_UPGRADE_REPORTS: 'VIEW_UPGRADE_REPORTS',

  // Settlement
  CREATE_SETTLEMENT: 'CREATE_SETTLEMENT',
  APPROVE_SETTLEMENT: 'APPROVE_SETTLEMENT',
  VIEW_SETTLEMENT_REPORTS: 'VIEW_SETTLEMENT_REPORTS',

  // Support CRM
  CREATE_SUPPORT_TICKET: 'CREATE_SUPPORT_TICKET',
  ASSIGN_SUPPORT_TICKET: 'ASSIGN_SUPPORT_TICKET',
  CLOSE_SUPPORT_TICKET: 'CLOSE_SUPPORT_TICKET',
  VIEW_SUPPORT_TICKETS: 'VIEW_SUPPORT_TICKETS',
  CREATE_COMPLAINT: 'CREATE_COMPLAINT',
  RESOLVE_COMPLAINT: 'RESOLVE_COMPLAINT',
  VIEW_CUSTOMER_TIMELINE: 'VIEW_CUSTOMER_TIMELINE',
  BLACKLIST_PASSENGER: 'BLACKLIST_PASSENGER',
  MANAGE_LOST_FOUND: 'MANAGE_LOST_FOUND',
  VIEW_SUPPORT_DASHBOARD: 'VIEW_SUPPORT_DASHBOARD',

  // Ticketing
  PRINT_TICKET: 'PRINT_TICKET',
  DOWNLOAD_TICKET: 'DOWNLOAD_TICKET',

  // Tracking
  GPS_PING: 'GPS_PING',
  VIEW_LIVE_TRACKING: 'VIEW_LIVE_TRACKING',
  MANAGE_GPS_PROVIDER: 'MANAGE_GPS_PROVIDER',
  CONFIGURE_GPS: 'CONFIGURE_GPS',
  MAP_GPS_DEVICE: 'MAP_GPS_DEVICE',

  // Trip
  CREATE_TRIP: 'CREATE_TRIP',
  CANCEL_TRIP: 'CANCEL_TRIP',
  ASSIGN_DRIVER: 'ASSIGN_DRIVER',
  START_TRIP: 'START_TRIP',
  END_TRIP: 'END_TRIP',
  VIEW_PASSENGER_MANIFEST: 'VIEW_PASSENGER_MANIFEST',

  // Workflow
  CREATE_APPROVAL_REQUEST: 'CREATE_APPROVAL_REQUEST',
  VIEW_APPROVAL_REQUESTS: 'VIEW_APPROVAL_REQUESTS',
  DECIDE_APPROVAL_REQUEST: 'DECIDE_APPROVAL_REQUEST',

} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

/** Human labels for the permission groups (used by the RBAC matrix screen). */
export const PERMISSION_GROUP_LABELS: Record<string, string> = {
  AUDIT: 'Audit',
  BOARDING: 'Boarding',
  BOOKING: 'Booking',
  BUS: 'Bus',
  CREW_HR: 'Crew HR',
  DISRUPTION: 'Disruption',
  DRIVER_COMPLIANCE: 'Driver Compliance',
  FLEET_MAINTENANCE: 'Fleet Maintenance',
  FORECASTING: 'Forecasting',
  FUEL: 'Fuel',
  HUB: 'Hub',
  OPERATOR_FINANCE: 'Operator Finance',
  OPERATOR_STAFF: 'Operator Staff',
  PASSENGER_TRANSFER: 'Passenger Transfer',
  PLATFORM_ANALYTICS: 'Platform Analytics',
  PLATFORM_API: 'Platform API',
  PLATFORM_BILLING: 'Platform Billing',
  PLATFORM_COMPLIANCE: 'Platform Compliance',
  PLATFORM_CONFIG: 'Platform Config',
  PLATFORM_MARKETPLACE: 'Platform Marketplace',
  PLATFORM_OPERATOR: 'Platform Operator',
  PLATFORM_RELIABILITY: 'Platform Reliability',
  PLATFORM_SUBSCRIPTION: 'Platform Subscription',
  PLATFORM_USER_SECURITY: 'Platform User Security',
  PRICING: 'Pricing',
  REFUND: 'Refund',
  REPORTS: 'Reports',
  ROUTE: 'Route',
  SCHEDULE: 'Schedule',
  SEAT_INVENTORY: 'Seat Inventory',
  SEAT_UPGRADE: 'Seat Upgrade',
  SETTLEMENT: 'Settlement',
  SUPPORT_CRM: 'Support CRM',
  TICKETING: 'Ticketing',
  TRACKING: 'Tracking',
  TRIP: 'Trip',
  WORKFLOW: 'Workflow',
};