import * as Joi from 'joi';
import { PLATFORM_DEFAULTS as D } from '../common/config/platform-defaults';
export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().allow('').required(),
  DB_NAME: Joi.string().required(),
  DB_SYNCHRONIZE: Joi.boolean().default(true),
  DB_LOGGING: Joi.boolean().default(false),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  MAX_BODY_SIZE: Joi.string().default('1mb'),
  LOGIN_MAX_ATTEMPTS: Joi.number().default(5),
  LOGIN_LOCK_MINUTES: Joi.number().default(15),
  JWT_ACCESS_EXPIRES: Joi.string().default('1d'),
  SMTP_HOST: Joi.string().default('smtp.gmail.com'),
  SMTP_PORT: Joi.number().default(587),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASS: Joi.string().allow('').optional(),
  SMTP_FROM: Joi.string().default('Yoo Bus <no-reply@yoobus.in>'),
  EMAIL_DEV_MODE: Joi.boolean().default(true),
  SETUP_FEE_PER_BUS: Joi.number().default(D.PAYMENT.setupFeePerBus),
  DEFAULT_COMMISSION_RATE: Joi.number().default(D.PAYMENT.defaultCommissionRate),
  FARE_GST_RATE: Joi.number().default(D.PAYMENT.fareGstRate),
  COMMISSION_GST_RATE: Joi.number().default(D.PAYMENT.commissionGstRate),
  TCS_RATE: Joi.number().default(D.PAYMENT.tcsRate),
  TDS_RATE: Joi.number().default(D.PAYMENT.tdsRate),
  SUPERADMIN_EMAIL: Joi.string().email().required(),
  SUPERADMIN_PASSWORD: Joi.string().min(8).required(),
  RAZORPAY_KEY_ID: Joi.string().allow('').optional(),
  RAZORPAY_KEY_SECRET: Joi.string().allow('').optional(),
}).unknown(true);
